### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by PulkitSingh256** [vpn/SMSSpoof#1]
For some some reason after submitting all the info it keeps on loading 
I can't see supported countries as well the area for supported countries is empty.
I just created a free Google I'd and used that to sign up for twilio and provided auth token and Sid to the config.php
![screenshot_20180203-170638](https://user-images.githubusercontent.com/24680989/35766803-a1f92084-0904-11e8-8a24-707ed394cac0.png)

**Comment by kreptotrash** [comment]
outdated libraries

**Comment by PulkitSingh256** [comment]
I am closing this issue Because all my balance was spent and maybe that's why

**Comment by vpn** [comment]
The problem with the supported country list was my fault, sorry about that.

**Comment by spankders** [comment]
> 
> 
> The problem with the supported country list was my fault, sorry about that.

so is there any willings to update the script ?
