### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by matrixcsz** [vpn/SMSSpoof#14]
![IMG_20201204_145547](https://user-images.githubusercontent.com/63876645/101132010-32eb7d00-3641-11eb-81cc-8987bd748c13.jpg)
Nothing happen just loading and loading...

**Comment by vpn** [comment]
@matrixcsz Are there any server-side errors? Anything in the developer tools console?

**Comment by matrixcsz** [comment]
Sorry what?

**Comment by matrixcsz** [comment]
> @matrixcsz Are there any server-side errors? Anything in the developer tools console?

Doesn't have any error just when i try to send sms nothing happen just stock in loadit

**Comment by f7aw7ess** [comment]
> > @matrixcsz Are there any server-side errors? Anything in the developer tools console?
> 
> Doesn't have any error just when i try to send sms nothing happen just stock in loading

Change your php version to 5.6. I had the same issue.
