### ISSUE TITLE
Stuck on loading !

### ISSUE THREAD

**Issue by VanStorek** [vpn/SMSSpoof#15]
hi there. 
I hosted the code on 000webhost and changed the (core/config.php) file with the AccountSID and AuthToken . and everything is fine but I get stuck on the loading screen !!

BTW the website is public so you can check it out and tell me what you think. 

https://peaceispower.000webhostapp.com/SMSSpoof/

**Comment by asierbarran** [comment]
Mee to :(

**Comment by asierbarran** [comment]
Any solution??

**Comment by arjentienkamp** [comment]
create_function in file assets/Services/Twilio/Resource.php is deprecated in PHP 7.2.

change line 74 to:

```
$callback = function ($matches) {
   return strtolower(strlen($matches[1]) ? $matches[1].$matches[2] : $matches[2]);
};
```

change line. 93 to:

```
$callback = function ($matches) {
   return strtoupper($matches[2]);
};

```

**Comment by f7aw7ess** [comment]
I had the same problem on 000webhost. I went to php configuration and changed the PHP version to 5.6 and now its working fine.
