### ISSUE TITLE
how can i fix this issue 

### ISSUE THREAD

**Issue by asciiterminal** [vpn/SMSSpoof#2]
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/SMSSpoof/core/functions/general.php:14
Stack trace:
#0 /root/SMSSpoof/index.php(77): getCountryListJson()
#1 {main}
  thrown in /root/SMSSpoof/core/functions/general.php on line 14
[Fri Jul 13 00:32:24 2018] ::1:38598 [200]: / - Uncaught Error: Call to undefined function curl_init() in /root/SMSSpoof/core/functions/general.php:14
Stack trace:
#0 /root/SMSSpoof/index.php(77): getCountryListJson()
#1 {main}
  thrown in /root/SMSSpoof/core/functions/general.php on line 14

**Comment by kel12345678** [comment]
hello how run this script give me the step

**Comment by vpn** [comment]
Make sure that you have cURL module enabled/installed. You can check this by looking at your phpinfo.

**Comment by vpn** [comment]
See fix in issue #3 or [(Direct)](https://github.com/vpn/SMSSpoof/issues/3#issuecomment-466248988).
