### ISSUE TITLE
dockerize main branch (php version)

### ISSUE THREAD

**Issue by vpn** [vpn/SMSSpoof#21]
This project should be Dockerized so that anyone can run it in a few clicks/commands.

**Comment by darkhacknet** [comment]
> This project should be Dockerized so that anyone can run it in a few clicks/commands.

Hey bro, hope you are well. 

So for now this is not working ? the site that we need to use to send messages seems to be down.

Thanks !

**Comment by darkhacknet** [comment]
> This project should be Dockerized so that anyone can run it in a few clicks/commands.

Or Please if this can work without the website Please tell me what commands can I use.

**Comment by bsisic** [comment]
#29
