### ISSUE TITLE
Keeps loading after hitting 'Send'

### ISSUE THREAD

**Issue by paradisiacor** [vpn/SMSSpoof#28]
It just keeps loading, it's set up on a localhost of Windows 10. The config file has been modified by adding the AccountSid and token.

![image](https://user-images.githubusercontent.com/46817310/143908787-e03dc964-1e3c-490b-a6c2-683277a19474.png)

**Comment by paradisiacor** [comment]
Tested on live server, still the same issue. No logs in Twilio error logger.

**Comment by vpn** [comment]
Any PHP errors? What web stack are you using locally?

**Comment by paradisiacor** [comment]
Hey, it's being tested on a live server. No visible errors in the console, it just keeps loading.

Apache Version | 2.4.51
-- | --
PHP Version | 5.6.40
MySQL Version | 10.3.32-MariaDB
Architecture | x86_64
Operating System | linux
Perl Version | 5.16.3
Kernel Version | 3.10.0-962.3.2.lve1.5.63.el7.x86_64

**Comment by paradisiacor** [comment]
![image](https://user-images.githubusercontent.com/46817310/144742796-38f108da-2a07-410a-995a-e3a9d9080908.png)

**Comment by f7aw7ess** [comment]
I've got the same issue. Just keeps loading after hitting send.
Any fix for this yet?

**Comment by f7aw7ess** [comment]
I had a similar issue, I changed my PHP version to 5.6 and now its working fine.

**Comment by cronotrigger1** [comment]
> I had a similar issue, I changed my PHP version to 5.6 and now its working fine.

@f7aw7ess: What is the code for installing version 5.6 that worked for you?
