### ISSUE TITLE
No response 

### ISSUE THREAD

**Issue by N0N3Hacker** [vpn/SMSSpoof#3]
Kali linux 2018.2 ,kali-rolling , running via virtual box.

I have followed every step carefully but i firstly i get this error:
Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/html/SMSSpoof/core/functions/general.php:14 Stack trace: #0 /var/www/html/SMSSpoof/index.php(77): getCountryListJson() #1 {main} thrown in /var/www/html/SMSSpoof/core/functions/general.php on line 14

i think thats because i am using the apache server and the file "SMSSpoof" must be in /var/www/SMSSpoof while i have it in /var/www/html/SMSspoof .Unfortunately if i have it in /var/www/SMSSpoof it does not appear in my server.

But the main reason that i am writing this is that i do not get any response after i have enter the Sender Recipient Message and i do not know if the message is send or not.

Help would be much appreciated!

**Comment by kel12345678** [comment]
Hello how run this script plsease give me the step

**Comment by vpn** [comment]
There shouldn't be an issue with the location of it on your web server, as long as you have configured the server to point to the directory of the files.

If you are using Apache then checkout these guides on Apache & Apache Virtual Hosts, 

- [Apache VirtualHost Documentation](https://httpd.apache.org/docs/2.4/vhosts/)
- [Apache VirtualHost Examples](https://httpd.apache.org/docs/2.4/vhosts/examples.html)
- [Digital Ocean Apache Setup guide](https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts)

With regards to your PHP error `Fatal error: Uncaught Error: Call to undefined function curl_init() ...`
This web application uses [cURL](http://php.net/manual/en/intro.curl.php) for making requests to APIs. 
Please make sure that you have enabled/installed it. You can check this via [phpinfo](http://php.net/manual/en/function.phpinfo.php) - Open phpinfo in a web browser and use `ctrl`+`f` to search for `cURL`. 
If you do not have the cURL module installed then follow the installation guide on the official PHP website, [here](http://php.net/manual/en/curl.installation.php), or you can always find a guide for your specific web server, operating system and PHP Version.
