### ISSUE TITLE
Walk-through

### ISSUE THREAD

**Issue by cronotrigger1** [vpn/SMSSpoof#30]
I'm such a newbie, I have no idea how to get this to work.  I started by trying to get apache to run in kali linux and it seemed to work.  Then I found that I didn't have an IP address or web server.  I didn't know how to proceed or add this into the code.  I thought I might be able to just use my computer IP but I don't even know how to do that.  So.  I couldn't even begin to apply your sms spoof code to the website and start a TWILIO account to direct sms messages to the webserver IP.  Would you be willing to give me a walk-through so I can get this up and running?

**Comment by youngzuwop2** [comment]
Did you ever get this to work?
