### ISSUE TITLE
Keeps loading after hitting send

### ISSUE THREAD

**Issue by kuato781** [vpn/SMSSpoof#31]
I have latest version of php installed on ubuntu -- when hitting "send" it just spins -- below is error in apache logs (referer obfuscated)

# php --version
PHP 8.0.14 (cli) (built: Dec 20 2021 21:23:34) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.14, Copyright (c), by Zend Technologies
    
# cat /etc/issue
Ubuntu 21.10 \n \l

# apache2 -v
Server version: Apache/2.4.48 (Ubuntu)
Server built:   2021-11-14T23:49:31
 

[Sun Jan 02 17:57:26.575904 2022] [php:error] [pid 28916] [client 69.244.55.115:52442] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /var/www/html/SMSSpoof/assets/Services/Twilio/Resource.php:93\nStack trace:\n#0 /var/www/html/SMSSpoof/assets/Services/Twilio/Resource.php(45): Services_Twilio_Resource::camelize()\n#1 /var/www/html/SMSSpoof/assets/Services/Twilio/Rest/Account.php(29): Services_Twilio_Resource->setupSubresources()\n#2 /var/www/html/SMSSpoof/assets/Services/Twilio/Resource.php(25): Services_Twilio_Rest_Account->init()\n#3 /var/www/html/SMSSpoof/assets/Services/Twilio/ListResource.php(44): Services_Twilio_Resource->__construct()\n#4 /var/www/html/SMSSpoof/assets/Services/Twilio.php(343): Services_Twilio_ListResource->get()\n#5 /var/www/html/SMSSpoof/send.php(45): Services_Twilio->__construct()\n#6 {main}\n  thrown in /var/www/html/SMSSpoof/assets/Services/Twilio/Resource.php on line 93, referer: http://XXXXXXXXXX/SMSSpoof/

**Comment by youngzuwop2** [comment]
did you get it resolved?
