### ISSUE TITLE
http://yourwebsite.io/SMSSPoof/ ????

### ISSUE THREAD

**Issue by darkhacknet** [vpn/SMSSpoof#33]
hey man hope you are well , could you be more precise with this expression ? 

"http://yourwebsite.io/SMSSPoof/"

Have you an example of that url ? 

thanks in advance
regards !

**Comment by itzdre420** [comment]
> 

Run a python http server in SMSSpoof directory

**Comment by itzdre420** [comment]
and then navigate there with your ip address

**Comment by darkhacknet** [comment]
> and then navigate there with your ip address

Thanks brotha, but Im only able to see my files located in the SMSSpoof folder !

**Comment by darkhacknet** [comment]
> and then navigate there with your ip address

Bro anytime that I try to enter to index.php the file index.php is downloaded ! So I cant enter to the site :/ 
Could you please tell me how to enter to the main site ? 

Thanks !

**Comment by youngzuwop2** [comment]
Is it still working for you guys?

**Comment by darkhacknet** [comment]
> Is it still working for you guys?

No man this seems to be not supported anymore, due to this I just coded my own telegram bot to send anonymous sms.
