### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by deadfishhackers** [vpn/SMSSpoof#5]
it didnt spoof sms but i noticed this

on supported countries section

**
Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/html/SMSSpoof/core/functions/general.php:14 Stack trace: #0 /var/www/html/SMSSpoof/index.php(77): getCountryListJson() #1 {main} thrown in /var/www/html/SMSSpoof/core/functions/general.php on line 14
**

**Comment by vpn** [comment]
Please see the answer in issue [#3 ](https://github.com/vpn/SMSSpoof/issues/3#issuecomment-466248988) or [(Direct)](https://github.com/vpn/SMSSpoof/issues/3#issuecomment-466248988)
