### ISSUE TITLE
Cannot get to work

### ISSUE THREAD

**Issue by saupe2005** [vpn/SMSSpoof#8]
Does this work in uk cannot get it to send message just spins and doesnt send any help would be apprieciated. thanks

**Comment by ADlL** [comment]
Hello,


Have you created an account on https://www.twilio.com/ ?

I guess that you'll need to sign up for an account, then retrieve the API.

**Comment by vpn** [comment]
@saupe2005 Did you get this to work?
Thanks @ADlL
