### ISSUE TITLE
code is broken

### ISSUE THREAD

**Issue by 5l1v3r1** [vpn/SMSSpoof#9]
::1]:34370 [200]: /send.php - Uncaught Error: Class 'Services_Twilio_Rest_OutgoingCallerids' not found in /var/www/SMSSpoof/assets/Services/Twilio/Resource.php:47
Stack trace:
#0 /var/www/SMSSpoof/assets/Services/Twilio/Rest/Account.php(29): Services_Twilio_Resource->setupSubresources('applications', 'available_phone...', 'outgoing_caller...', 'calls', 'conferences', 'incoming_phone_...', 'keys', 'media', 'messages', 'notifications', 'outgoing_caller...', 'recordings', 'sms_messages', 'short_codes', 'tokens', 'transcriptions', 'connect_apps', 'authorized_conn...', 'usage_records', 'usage_triggers', 'queues', 'sip', 'addresses')
#1 /var/www/SMSSpoof/assets/Services/Twilio/Resource.php(25): Services_Twilio_Rest_Account->init(Object(Services_Twilio), '/2010-04-01/Acc...')
#2 /var/www/SMSSpoof/assets/Services/Twilio/ListResource.php(44): Services_Twilio_Resource->__construct(Object(Services_Twilio), '/2010-04-01/Acc...')
#3 /var/www/SMSSpoof/assets/Services/Twilio.php(343): Services_Twilio_ListResource->get('ACc2b110c641cdd...')
#4 /var/www/S in /var/www/SMSSpoof/assets/Services/Twilio/Resource.php on line 47

**Comment by vpn** [comment]
Can you confirm which version of the Twilio API you are using?
